// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk6ijVE_OvgIIXjGp553fPZGmLdfS4Fag',
    appId: '1:138365380070:web:1b7d918797871860f06227',
    messagingSenderId: '138365380070',
    projectId: 'rooted-f95c7',
    authDomain: 'rooted-f95c7.firebaseapp.com',
    storageBucket: 'rooted-f95c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjrDdhIjUR-71CFDhlbNuJ5oAvgqytBM4',
    appId: '1:138365380070:android:067a9b67eada1e09f06227',
    messagingSenderId: '138365380070',
    projectId: 'rooted-f95c7',
    storageBucket: 'rooted-f95c7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo-6txuoSIh9Kmp3ET-kTGoFGdbRoL-oI',
    appId: '1:138365380070:ios:742dda45c3b45b25f06227',
    messagingSenderId: '138365380070',
    projectId: 'rooted-f95c7',
    storageBucket: 'rooted-f95c7.firebasestorage.app',
    androidClientId: '138365380070-001ntuqrfsqp9oo9cuaclq9smv6c3jns.apps.googleusercontent.com',
    iosClientId: '138365380070-6oh8otausd6s64ejt1q3idb50ibnenmb.apps.googleusercontent.com',
    iosBundleId: 'yes',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo-6txuoSIh9Kmp3ET-kTGoFGdbRoL-oI',
    appId: '1:138365380070:ios:742dda45c3b45b25f06227',
    messagingSenderId: '138365380070',
    projectId: 'rooted-f95c7',
    storageBucket: 'rooted-f95c7.firebasestorage.app',
    androidClientId: '138365380070-001ntuqrfsqp9oo9cuaclq9smv6c3jns.apps.googleusercontent.com',
    iosClientId: '138365380070-6oh8otausd6s64ejt1q3idb50ibnenmb.apps.googleusercontent.com',
    iosBundleId: 'yes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk6ijVE_OvgIIXjGp553fPZGmLdfS4Fag',
    appId: '1:138365380070:web:2aa5fbe085aacfc7f06227',
    messagingSenderId: '138365380070',
    projectId: 'rooted-f95c7',
    authDomain: 'rooted-f95c7.firebaseapp.com',
    storageBucket: 'rooted-f95c7.firebasestorage.app',
  );
}
