// Builds the ANIMATED launch splash for Android 12+ — it plays the instant
// the app icon is pressed, before Flutter has even started: the kuwaGO
// lockup (lib/art/wordmark_art.dart) on leaf green; the clock O's minute
// hand winds one full lap while kuwago, perched on the clock, bobs twice.
//
//   android/app/src/main/res/drawable/splash_lockup_anim.xml  (animated vector)
//
// It also points the Android 12 splash styles at it. flutter_native_splash
// rewrites those styles, so ALWAYS run this right after it:
//
//   dart run flutter_native_splash:create
//   dart run tool/generate_splash_anim.dart
//
// The last frame equals the first (10:10, owl at rest), which is exactly
// what the opening in the app (lib/widgets/clock_intro.dart) starts from.

import 'dart:io';
import 'package:rooted/art/owl_art.dart';
import 'package:rooted/art/wordmark_art.dart';

const _resDir = 'android/app/src/main/res';
const _drawable = 'splash_lockup_anim';

// The splash icon is 288×288 dp (Android 12, no icon background), drawn
// here as 1 unit = 1 dp, with the lockup centred on (144, 144).
const _viewport = 288;
const _px = lockupPixelDp;
const _left = _viewport / 2 - lockupWidth * _px / 2;
const _top = _viewport / 2 - lockupHeight * _px / 2;

// Wind-up timing (ms): 13 minute-hand frames, 5 minutes apart.
const _firstStep = 60;
const _stepMs = 65;

String _hex(int argb) => '#${argb.toRadixString(16).padLeft(8, '0').toUpperCase()}';
String _n(double v) => v.toStringAsFixed(2);

/// Path data for pixels in lockup coordinates, one string per colour.
Map<int, StringBuffer> _paths(Iterable<(int, int, int)> pixels) {
  final out = <int, StringBuffer>{};
  for (final (x, y, color) in pixels) {
    final l = _left + (x - lockupLeft) * _px, t = _top + (y - lockupTop) * _px;
    out.putIfAbsent(color, StringBuffer.new).write('M${_n(l)},${_n(t)}h${_n(_px)}v${_n(_px)}h-${_n(_px)}z');
  }
  return out;
}

void main() {
  final out = StringBuffer()
    ..writeln('<?xml version="1.0" encoding="utf-8"?>')
    ..writeln('<!-- GENERATED by tool/generate_splash_anim.dart. Do not edit by hand. -->')
    ..writeln('<animated-vector xmlns:android="http://schemas.android.com/apk/res/android"')
    ..writeln('    xmlns:aapt="http://schemas.android.com/aapt">')
    ..writeln('    <aapt:attr name="android:drawable">')
    ..writeln('        <vector android:width="${_viewport}dp" android:height="${_viewport}dp"')
    ..writeln('            android:viewportWidth="$_viewport" android:viewportHeight="$_viewport">');
  void emit(Map<int, StringBuffer> paths, String indent, {String? name, double alpha = 1}) {
    paths.forEach((color, d) {
      final n = name == null ? '' : ' android:name="$name"';
      final a = alpha == 1 ? '' : ' android:fillAlpha="$alpha"';
      out.writeln('$indent<path$n android:fillColor="${_hex(color)}"$a android:pathData="$d"/>');
    });
  }

  // Letters (with their soft shadow).
  emit(_paths(letterPixels()), '            ');

  // Clock body + hour hand (fixed at 10).
  final clock = [
    for (final (x, y, c) in clockBodyPixels()) (x + clockLeft, y, c),
    for (final (x, y) in clockHand(restHour / 12, hourHandLength)) (x + clockLeft, y, clockHourHand),
  ];
  emit(_paths(clock), '            ');

  // Minute hand: one path per 5-minute step, only one visible at a time.
  const frames = 13; // 10, 15, … 55, 0, 5, 10 — ends where it started
  for (var k = 0; k < frames; k++) {
    final minute = restMinute + k * 5;
    final hand = [for (final (x, y) in clockHand(minute / 60, minuteHandLength)) (x + clockLeft, y, clockMinuteHand)];
    emit(_paths(hand), '            ', name: 'minute_$k', alpha: k == 0 ? 1 : 0);
  }
  emit(_paths([for (final (x, y) in clockPin) (x + clockLeft, y, clockOutline)]), '            ');

  // kuwago, perched on the clock (bobs).
  final owl = owlRows(perch: false);
  final owlPixels = <(int, int, int)>[
    for (var y = 0; y < owl.length; y++)
      for (var x = 0; x < owl[y].length; x++)
        if (owlColors[owl[y][x]] != null) (x + owlLeft, y + owlTop, owlColors[owl[y][x]]!),
  ];
  out.writeln('            <group android:name="owl">');
  emit(_paths(owlPixels), '                ');
  out
    ..writeln('            </group>')
    ..writeln('        </vector>')
    ..writeln('    </aapt:attr>');

  void target(String name, List<String> animators) {
    out
      ..writeln('    <target android:name="$name">')
      ..writeln('        <aapt:attr name="android:animation">')
      ..writeln('            <set>');
    for (final a in animators) {
      out.writeln('                $a');
    }
    out
      ..writeln('            </set>')
      ..writeln('        </aapt:attr>')
      ..writeln('    </target>');
  }

  String anim(String prop, num from, num to, int start, int duration, [String interp = 'accelerate_decelerate_interpolator']) =>
      '<objectAnimator android:propertyName="$prop" android:valueFrom="$from" android:valueTo="$to" '
      'android:startOffset="$start" android:duration="$duration" android:valueType="floatType" '
      'android:interpolator="@android:anim/$interp"/>';

  for (var k = 0; k < frames; k++) {
    final shownAt = _firstStep + k * _stepMs;
    target('minute_$k', [
      if (k > 0) anim('fillAlpha', 0, 1, shownAt, 1, 'linear_interpolator'),
      if (k < frames - 1) anim('fillAlpha', 1, 0, shownAt + _stepMs, 1, 'linear_interpolator'),
    ]);
  }
  // Two little bobs, back at rest by the end.
  target('owl', [
    anim('translateY', 0, -5, 100, 150, 'decelerate_interpolator'),
    anim('translateY', -5, 0, 250, 150, 'accelerate_interpolator'),
    anim('translateY', 0, -5, 450, 150, 'decelerate_interpolator'),
    anim('translateY', -5, 0, 600, 150, 'accelerate_interpolator'),
  ]);
  out.writeln('</animated-vector>');

  File('$_resDir/drawable/$_drawable.xml').writeAsStringSync(out.toString());
  stdout.writeln('Wrote $_resDir/drawable/$_drawable.xml');

  // Point the Android 12 splash at it (light + dark styles).
  for (final dir in ['values-v31', 'values-night-v31']) {
    final file = File('$_resDir/$dir/styles.xml');
    if (!file.existsSync()) continue;
    var xml = file.readAsStringSync();
    xml = xml.replaceAll(
      RegExp(r'<item name="android:windowSplashScreenAnimatedIcon">[^<]*</item>'),
      '<item name="android:windowSplashScreenAnimatedIcon">@drawable/$_drawable</item>',
    );
    if (!xml.contains('windowSplashScreenAnimationDuration')) {
      xml = xml.replaceFirst(
        '@drawable/$_drawable</item>',
        '@drawable/$_drawable</item>\n        <item name="android:windowSplashScreenAnimationDuration">1000</item>',
      );
    }
    file.writeAsStringSync(xml);
    stdout.writeln('Updated $_resDir/$dir/styles.xml');
  }
}
